DF-2911: TRACE filter (autoconfigured spring boot library)
alv-ch/alv-shared-library pull request #43
Opened 2020-10-13 10:33 UTC by palsch

2020-10-13 10:39 UTC, birom commented on alv-trace-filter-starter/src/main/java/ch/admin/seco/alv/shared/trace/filter/TraceFilter.java
> +        if (properties.isEnabled() && request.getMethod().equalsIgnoreCase("TRACE")) {
Should not we disallow ``TRACK`` as well?

2020-10-13 10:39 UTC, birom commented on alv-trace-filter-starter/pom.xml
> +            <groupId>org.springframework.boot</groupId>
Why do we need the undertow dependency?

2020-10-13 11:05 UTC, palsch commented on alv-trace-filter-starter/src/main/java/ch/admin/seco/alv/shared/trace/filter/TraceFilter.java
> +        if (properties.isEnabled() && request.getMethod().equalsIgnoreCase("TRACE")) {
done

2020-10-13 11:06 UTC, palsch commented on alv-trace-filter-starter/pom.xml
> +            <groupId>org.springframework.boot</groupId>
we need that for all "import javax.servlet.*" classes

2020-10-13 11:09 UTC, birom commented on alv-trace-filter-starter/pom.xml
> +            <groupId>org.springframework.boot</groupId>
I thinks we should set it to ``provided``, if a client project uses ``tomcat`` instead of ``undertow``.

2020-10-13 11:37 UTC, seco-mgabor requested changes

2020-10-13 11:37 UTC, seco-mgabor commented on alv-trace-filter-starter/src/main/java/ch/admin/seco/alv/shared/trace/filter/TraceFilter.java
> +
I think the name is misleading: we block both TRACE and TRACK methods. The name should be more generic, not containing plain "Trace".
Also, there's only 1 property, named "alv.trace.filter". This should refer to TRACE only, as the name says. Or do you intend to introduce an "alv.track.filter" too?

2020-10-13 11:37 UTC, seco-mgabor commented on alv-trace-filter-starter/src/main/java/ch/admin/seco/alv/shared/trace/filter/TraceFilter.java
> +        if (properties.isEnabled() && Stream.of("TRACE", "TRACK").anyMatch(m -> request.getMethod().equalsIgnoreCase(m))) {
Why don't you use the HTTPMethod API instead of magic strings?

2020-10-13 12:00 UTC, palsch commented on alv-trace-filter-starter/src/main/java/ch/admin/seco/alv/shared/trace/filter/TraceFilter.java
> +
According to the w3 http 1.1 standard, there is no TRACK method available: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

"The HTTP TRACK method is something Microsoft cooked up that performs essentially the same thing that TRACE does with the exception that it never got used—except by penetration testers, hackers, worms, and vulnerability scanners." (https://www.techstacks.com/howto/disable-tracetrack-in-apache-httpd.html)

HTTP TRACK is an unknown method inside the spring application and will be blocked.

I still added that to be save on our side, but I would rename the complete library because of this method.

2020-10-13 12:01 UTC, palsch commented on alv-trace-filter-starter/src/main/java/ch/admin/seco/alv/shared/trace/filter/TraceFilter.java
> +        if (properties.isEnabled() && Stream.of("TRACE", "TRACK").anyMatch(m -> request.getMethod().equalsIgnoreCase(m))) {
HttpMethod API does not contain the TRACK method, see my comment below.
I wanted to be consisten, so added also the TRACE method as a string.

2020-10-13 12:08 UTC, seco-mgabor commented on alv-trace-filter-starter/src/main/java/ch/admin/seco/alv/shared/trace/filter/TraceFilter.java
> +
A real big mess this HTTP.TRACK.  :(
I wasn't aware of that.

2020-10-13 12:51 UTC, birom approved these changes

2020-10-14 11:08 UTC, seco-mgabor approved these changes

2020-10-14 11:44 UTC, merged